requests:
  - path: /foo
    headers:
      content-type: "application/json"
      accept: "(application/json)|(\\*/\\*)"
    method: GET
    response:
      headers:
        content-type: "application/json; charset=utf-8"
      body:
        users:
          - id: 1
            name: "John Doe"
          - id: 2
            name: "Jane Smith"
      status-code: 200
  - path: /foo
    headers:
      content-type: ".*"
    method: POST
    body: ".*foo.*"
    response:
      headers:
        content-type: "application/json"
      status-code: 201
  - path: /search
    method: GET
    queryParams:
      q: ".+"
      page: "[0-9]+"
    response:
      headers:
        content-type: "application/json"
      body:
        results: []
        query: "example"
      status-code: 200
  - path: /slow-endpoint
    method: GET
    responseDelay:
      min: 500
      max: 1500
    response:
      headers:
        content-type: "application/json"
      body:
        message: "This response was delayed"
      status-code: 200
  - path: /random-json
    method: GET
    response:
      status-code: 200
      headers:
        content-type: "application/json"
      randomBody:
        type: json
        size: "2 gB"
  - path: /random-text
    method: GET
    response:
      status-code: 200
      randomBody:
        type: plaintext
        size: "512"
  - path: /random-xml
    method: GET
    response:
      status-code: 200
      headers:
        content-type: "application/xml"
      randomBody:
        type: xml
        size: "1 KB"